[supabase]
url = "https://xqztjxubdspuuybootox.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxenRqeHViZHNwdXV5Ym9vdG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwNTU2ODUsImV4cCI6MjA4MTYzMTY4NX0.kx8QKP7uh4JJ5lasnphcMNKXHZJBMUBGLW7FVHM3VR8"
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxenRqeHViZHNwdXV5Ym9vdG94Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjA1NTY4NSwiZXhwIjoyMDgxNjMxNjg1fQ.N4SLnOAIG37r9G33luEJHAZ6ZKbsO06uLFwqx8KY2m4"

[google]
api_key = "AIzaSyBHn5o9eagWjqXEpwm-Q8CyRDefnbQJ9fE"
